import type { Tier } from '../composables/useTier'

export interface MenuItem {
  label: string
  icon: string
  route?: string
  tier: Tier
  children?: MenuItem[]
}

export const menuItems: MenuItem[] = [
  {
    label: 'Dashboard',
    icon: '⌂',
    route: '/dashboard',
    tier: 'standard',
    children: [
      { label: 'Overview', route: '/dashboard', tier: 'standard', icon: '' },
      { label: 'Health Score', route: '/dashboard/health-score', tier: 'plus', icon: '' },
      { label: 'Global Map', route: '/dashboard/global-map', tier: 'plus', icon: '' },
      { label: 'Custom Dashboards', route: '/dashboard/custom', tier: 'plus', icon: '' },
      { label: 'Helicopter View', route: '/dashboard/helicopter', tier: 'plus', icon: '' },
    ],
  },
  {
    label: 'Power Management',
    icon: '⚡',
    route: '/power',
    tier: 'standard',
    children: [
      { label: 'Overview', route: '/power', tier: 'standard', icon: '' },
      { label: 'PUE Monitoring', route: '/power/pue', tier: 'standard', icon: '' },
      { label: 'PUE Advanced', route: '/power/pue-advanced', tier: 'plus', icon: '' },
      { label: 'Budget Capacity', route: '/power/budget-capacity', tier: 'plus', icon: '' },
      { label: 'Active Power', route: '/power/active-power', tier: 'plus', icon: '' },
      { label: 'Distribution & Redundancy', route: '/power/distribution', tier: 'plus', icon: '' },
      { label: 'Stranded Analysis', route: '/power/stranded', tier: 'platinum', icon: '' },
      { label: 'DC Power Control', route: '/power/dpc', tier: 'plus', icon: '' },
      { label: 'Battery Management', route: '/power/battery', tier: 'plus', icon: '' },
      { label: 'Power Quality', route: '/power/quality', tier: 'platinum', icon: '' },
      { label: 'Server Power', route: '/power/server-power', tier: 'standard', icon: '' },
      { label: 'Server Heatmap', route: '/power/server-heatmap', tier: 'plus', icon: '' },
      { label: 'Port Capacity', route: '/power/port-capacity', tier: 'plus', icon: '' },
      { label: 'Energy Cost & Billing', route: '/power/energy-cost', tier: 'platinum', icon: '' },
      { label: 'UPS Monitoring', route: '/power/ups', tier: 'standard', icon: '' },
      { label: 'Breakers Utilization', route: '/power/breakers', tier: 'platinum', icon: '' },
    ],
  },
  {
    label: 'Cooling Management',
    icon: '❄',
    route: '/cooling',
    tier: 'standard',
    children: [
      { label: 'Overview', route: '/cooling', tier: 'standard', icon: '' },
      { label: 'Efficiency', route: '/cooling/efficiency', tier: 'plus', icon: '' },
      { label: 'Temperature', route: '/cooling/temperature', tier: 'standard', icon: '' },
      { label: 'Humidity', route: '/cooling/humidity', tier: 'plus', icon: '' },
      { label: 'Sensors Trend', route: '/cooling/sensors-trend', tier: 'plus', icon: '' },
      { label: 'Capacity Planning', route: '/cooling/capacity-planning', tier: 'platinum', icon: '' },
      { label: 'Supply & Return Air', route: '/cooling/supply-return', tier: 'plus', icon: '' },
      { label: 'Water Usage (WUE)', route: '/cooling/wue', tier: 'platinum', icon: '' },
      { label: 'System Status', route: '/cooling/system-status', tier: 'standard', icon: '' },
      { label: 'Chiller Efficiency', route: '/cooling/chiller', tier: 'platinum', icon: '' },
      { label: 'Airflow Monitoring', route: '/cooling/airflow', tier: 'platinum', icon: '' },
      { label: 'Sensor Management', route: '/cooling/sensors', tier: 'plus', icon: '' },
    ],
  },
  {
    label: 'Space Management',
    icon: '🏗',
    route: '/space',
    tier: 'standard',
    children: [
      { label: 'Overview', route: '/space', tier: 'standard', icon: '' },
      { label: 'Rack Utilization', route: '/space/rack-utilization', tier: 'standard', icon: '' },
      { label: 'Gap Analysis', route: '/space/gap-analysis', tier: 'plus', icon: '' },
      { label: 'Cabinet Remaining', route: '/space/cabinet-remaining', tier: 'plus', icon: '' },
      { label: 'Floor Plan', route: '/space/floor-plan', tier: 'plus', icon: '' },
      { label: 'Rack Elevation', route: '/space/rack-elevation', tier: 'plus', icon: '' },
      { label: 'What-If Planning', route: '/space/what-if', tier: 'platinum', icon: '' },
      { label: 'Site Hierarchy', route: '/space/site-hierarchy', tier: 'standard', icon: '' },
      { label: 'Storage Tracking', route: '/space/storage', tier: 'standard', icon: '' },
      { label: 'Asset Placement', route: '/space/asset-placement', tier: 'platinum', icon: '' },
    ],
  },
  {
    label: 'Network & Connectivity',
    icon: '🌐',
    route: '/network',
    tier: 'standard',
    children: [
      { label: 'Overview', route: '/network', tier: 'standard', icon: '' },
      { label: 'Traffic', route: '/network/traffic', tier: 'standard', icon: '' },
      { label: 'Data Ports', route: '/network/data-ports', tier: 'plus', icon: '' },
      { label: 'Power Ports', route: '/network/power-ports', tier: 'plus', icon: '' },
      { label: 'Port Properties', route: '/network/port-properties', tier: 'plus', icon: '' },
      { label: 'Cable Tracing', route: '/network/cable-tracing', tier: 'platinum', icon: '' },
      { label: 'Containers', route: '/network/containers', tier: 'standard', icon: '' },
      { label: 'Topology', route: '/network/topology', tier: 'platinum', icon: '' },
    ],
  },
  {
    label: 'Server & Assets',
    icon: '🖥',
    route: '/assets',
    tier: 'standard',
    children: [
      { label: 'Server Metrics', route: '/assets/server-metrics', tier: 'standard', icon: '' },
      { label: 'Server Heatmap', route: '/assets/server-heatmap', tier: 'plus', icon: '' },
      { label: 'Server Status', route: '/assets/server-status', tier: 'standard', icon: '' },
      { label: 'Inventory', route: '/assets/inventory', tier: 'standard', icon: '' },
      { label: 'By Model', route: '/assets/by-model', tier: 'plus', icon: '' },
      { label: 'By Status', route: '/assets/by-status', tier: 'plus', icon: '' },
      { label: 'Parts Inventory', route: '/assets/parts', tier: 'plus', icon: '' },
      { label: 'Physical / Virtual', route: '/assets/physical-virtual', tier: 'plus', icon: '' },
      { label: 'By OS', route: '/assets/by-os', tier: 'plus', icon: '' },
      { label: 'Item Age Tracking', route: '/assets/item-age', tier: 'platinum', icon: '' },
      { label: 'By Attributes', route: '/assets/by-attributes', tier: 'platinum', icon: '' },
      { label: 'Lifecycle', route: '/assets/lifecycle', tier: 'platinum', icon: '' },
      { label: 'Bulk Import / Export', route: '/assets/bulk', tier: 'plus', icon: '' },
    ],
  },
  {
    label: 'Environmental',
    icon: '🌿',
    route: '/environmental',
    tier: 'standard',
    children: [
      { label: 'Carbon Footprint', route: '/environmental', tier: 'standard', icon: '' },
      { label: 'Sustainability', route: '/environmental/sustainability', tier: 'plus', icon: '' },
      { label: 'Renewables', route: '/environmental/renewables', tier: 'platinum', icon: '' },
      { label: 'Carbon Offset', route: '/environmental/carbon-offset', tier: 'platinum', icon: '' },
      { label: 'ERE', route: '/environmental/ere', tier: 'platinum', icon: '' },
      { label: 'Scope 1/2/3 Emissions', route: '/environmental/emissions', tier: 'platinum', icon: '' },
      { label: 'Energy Storage', route: '/environmental/energy-storage', tier: 'platinum', icon: '' },
      { label: 'DCOI Compliance', route: '/environmental/dcoi', tier: 'platinum', icon: '' },
      { label: 'ESG Reporting', route: '/environmental/esg', tier: 'platinum', icon: '' },
    ],
  },
  {
    label: 'Security',
    icon: '🔒',
    route: '/security',
    tier: 'standard',
    children: [
      { label: 'Overview', route: '/security', tier: 'standard', icon: '' },
      { label: 'Physical Security', route: '/security/physical', tier: 'plus', icon: '' },
      { label: 'Cybersecurity', route: '/security/cyber', tier: 'platinum', icon: '' },
      { label: 'Access Control', route: '/security/access-control', tier: 'standard', icon: '' },
      { label: 'CCTV Integration', route: '/security/cctv', tier: 'platinum', icon: '' },
      { label: 'Audit Log', route: '/security/audit-log', tier: 'plus', icon: '' },
    ],
  },
  {
    label: 'Alarms & Notifications',
    icon: '🚨',
    route: '/alarms',
    tier: 'standard',
    children: [
      { label: 'Active Alarms', route: '/alarms', tier: 'standard', icon: '' },
      { label: 'Alarm History', route: '/alarms/history', tier: 'standard', icon: '' },
      { label: 'Notification Center', route: '/alarms/notifications', tier: 'standard', icon: '' },
      { label: 'Email Alerts', route: '/alarms/email', tier: 'standard', icon: '' },
      { label: 'SMS Notifications', route: '/alarms/sms', tier: 'plus', icon: '' },
      { label: 'Push Notifications', route: '/alarms/push', tier: 'platinum', icon: '' },
      { label: 'Custom Rules', route: '/alarms/rules', tier: 'plus', icon: '' },
      { label: 'Escalation Policies', route: '/alarms/escalation', tier: 'platinum', icon: '' },
      { label: 'Maintenance Scheduling', route: '/alarms/maintenance', tier: 'plus', icon: '' },
      { label: 'Analyze Warnings', route: '/alarms/analyze', tier: 'platinum', icon: '' },
    ],
  },
  {
    label: 'Change Management',
    icon: '📋',
    route: '/changes',
    tier: 'plus',
    children: [
      { label: 'Pending Requests', route: '/changes', tier: 'plus', icon: '' },
      { label: 'Completed Requests', route: '/changes/completed', tier: 'plus', icon: '' },
      { label: 'Request Types', route: '/changes/types', tier: 'plus', icon: '' },
      { label: 'Work Orders', route: '/changes/work-orders', tier: 'platinum', icon: '' },
      { label: 'Audit Log', route: '/changes/audit-log', tier: 'platinum', icon: '' },
      { label: 'Approval Workflows', route: '/changes/approvals', tier: 'platinum', icon: '' },
    ],
  },
  {
    label: 'Reports & Analytics',
    icon: '📊',
    route: '/reports',
    tier: 'standard',
    children: [
      { label: 'Standard Reports', route: '/reports', tier: 'standard', icon: '' },
      { label: 'PUE Trends', route: '/reports/pue-trends', tier: 'plus', icon: '' },
      { label: 'Capacity Reports', route: '/reports/capacity', tier: 'plus', icon: '' },
      { label: 'Export CSV', route: '/reports/export-csv', tier: 'standard', icon: '' },
      { label: 'Export PDF / Excel', route: '/reports/export-pdf', tier: 'plus', icon: '' },
      { label: 'Scheduled Reports', route: '/reports/scheduled', tier: 'platinum', icon: '' },
      { label: 'ISO 22237 Compliance', route: '/reports/iso-compliance', tier: 'platinum', icon: '' },
      { label: 'Concise / Detailed Mode', route: '/reports/mode-toggle', tier: 'plus', icon: '' },
      { label: 'Heatmap Reports', route: '/reports/heatmap', tier: 'platinum', icon: '' },
    ],
  },
  {
    label: 'Settings',
    icon: '⚙',
    route: '/settings',
    tier: 'standard',
    children: [
      { label: 'User Management', route: '/settings', tier: 'standard', icon: '' },
      { label: 'RBAC', route: '/settings/rbac', tier: 'standard', icon: '' },
      { label: 'System Config', route: '/settings/system', tier: 'standard', icon: '' },
      { label: 'Site Management', route: '/settings/sites', tier: 'standard', icon: '' },
      { label: 'Integrations', route: '/settings/integrations', tier: 'platinum', icon: '' },
      { label: 'API Access', route: '/settings/api', tier: 'plus', icon: '' },
      { label: 'Webhooks', route: '/settings/webhooks', tier: 'platinum', icon: '' },
      { label: 'Sensor Config', route: '/settings/sensors', tier: 'standard', icon: '' },
      { label: 'SSO / LDAP', route: '/settings/sso', tier: 'platinum', icon: '' },
      { label: 'Audit Logs', route: '/settings/audit-logs', tier: 'plus', icon: '' },
      { label: 'Multi-language', route: '/settings/language', tier: 'platinum', icon: '' },
    ],
  },
  {
    label: 'Visualization',
    icon: '🌍',
    route: '/visualization',
    tier: 'plus',
    children: [
      { label: 'Floor Plan', route: '/visualization', tier: 'plus', icon: '' },
      { label: '3D View', route: '/visualization/3d', tier: 'platinum', icon: '' },
      { label: 'Rack Elevation', route: '/visualization/rack-elevation', tier: 'plus', icon: '' },
      { label: 'Power Heatmap', route: '/visualization/power-heatmap', tier: 'plus', icon: '' },
      { label: 'Temperature Heatmap', route: '/visualization/temp-heatmap', tier: 'platinum', icon: '' },
      { label: 'Utilization Heatmap', route: '/visualization/util-heatmap', tier: 'platinum', icon: '' },
      { label: 'Network Topology', route: '/visualization/topology', tier: 'platinum', icon: '' },
      { label: 'Custom Widgets', route: '/visualization/widgets', tier: 'platinum', icon: '' },
      { label: 'Weather Widgets', route: '/visualization/weather', tier: 'platinum', icon: '' },
    ],
  },
]
